services:
  mysql-tcc:
    image: mysql:latest
    container_name: tcc-db
    volumes:
      - ~/.local/state/docker-volumes/sistemas/mysql-tcc/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nec
